const

  MaxErrStrID                             = 33444;
  ecCannotCreateExcel                     = MaxErrStrID - 1;
  ecWorkbookNotFound                      = MaxErrStrID - 2;
  ecSheetNotFound                         = MaxErrStrID - 3;
  ecRangeNotFound                         = MaxErrStrID - 4;
  ecMacroRuntimeError                     = MaxErrStrID - 5;
  ecReportOptionError                     = MaxErrStrID - 6;
  ecSheetOptionError                      = MaxErrStrID - 7;
  ecSaveInTempError                       = MaxErrStrID - 8;
  ecDataSetNotOpen                        = MaxErrStrID - 9;
  ecPrinterNotFound                       = MaxErrStrID - 10;
  ecExcelConnectionPointError             = MaxErrStrID - 11;
  ecTemplateAlreadyOpen                   = MaxErrStrID - 12;
  ecExcelDDENotAvailable                  = MaxErrStrID - 13;
  ecTemplateNotFound                      = MaxErrStrID - 14;
  ecIncorrectRangeFormat                  = MaxErrStrID - 15;
  ecOLEContainerError                     = MaxErrStrID - 16;
  ecOptionParameterNotFound               = MaxErrstrID - 20;
  ecOptionParameterValueIncorrectType     = MaxErrstrID - 21;
  ecCannotCreateName                      = MaxErrstrID - 22;
  ecMultisheetFieldNotFound               = MaxErrstrID - 23;
  ecMultisheetDataSourceNotFound          = MaxErrstrID - 24;
  ecDataSourceNotFound                    = MaxErrStrID - 25;
  ecAliasAlreadyExists                    = MaxErrStrID - 26;
  ecNameNotValid                          = MaxErrStrID - 27;
  ecMultisheetNotAvailable                = MaxErrStrID - 28;
  ecFileNotFound                          = MaxErrStrID - 29;
  ecCannotUsMSDataSource                  = MaxErrStrID - 30;
  ecParameterAlreadyExist                 = MaxErrStrID - 31;
  ecExcelNotInstalled                     = MaxErrStrID - 55;
  ecIncorrectExcelApp                     = MaxErrStrID - 56;
  ecIncorrectWbk                          = MaxErrStrID - 57;

  MaxMsgStrID                             = 33777;
  msgComponentMenuEdit                    = MaxMsgStrID - 1;
  msgComponentMenuBuild                   = MaxMsgStrID - 2;
  msgComponentMenuAbout                   = MaxMsgStrID - 3;
  msgPropertyEditorFileOpen               = MaxMsgStrID - 4;
  msgPropertyEditorSelectTemplate         = MaxMsgStrID - 5;
  msgPropertyEditorSelectTempPath         = MaxMsgStrID - 6;
  msgComponentMenuBuildDebug              = MaxMsgStrID - 7;
  msgAddDataSourceprohibited              = MaxMsgStrID - 8;
  msgConfirmRangePropertyChange           = MaxMsgStrID - 10;
  msgComponentMenuRefresh                 = MaxMsgStrID - 11;

